export ZSH="$HOME/.oh-my-zsh"
export VISUAL=nvim;
export EDITOR=nvim;
export GOPATH="/home/dvragulin/.go"
PATH=$PATH:$GOPATH/bin # Add GOPATH/bin to PATH for scripting
export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=full --line-range :300 {}'"
export BAT_THEME="ansi"
export ZSH_TMUX_AUTOSTART=false
export ZSH_TMUX_AUTOQUIT=true
export ZSH_TMUX_AUTOCONNECT=false
export TERM=xterm-256color

ZSH_THEME="af-magic"
DISABLE_AUTO_UPDATE="true"

plugins=(
   sudo 
   zsh-syntax-highlighting
   tmux
   # Auto start tmux
   #https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux
)

source $ZSH/oh-my-zsh.sh

# User configuration
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# k8s aliases
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases

# Other aliases
alias vim="nvim"
alias mk="minikube"
alias mail="neomutt"
alias email="neomutt"
alias vf='nvim $(fzf)'
alias cf='cat $(fzf)'
alias yt='ytfzf'
alias h='history'
alias r='ranger'
alias mkdir='mkdir -p'
alias t='tmux'
#alias ts='tmux list-sessions'
alias tf='terraform'
alias tfm='terraformer'
alias kp='keepassxc'
alias ap='ansible-playbook'
alias pwg='makepasswd --chars=32 --count=5'
alias youtube-watch='yt'
alias youtube-download-audio='yt-dlp -x --audio-format mp3 --cookies-from-browser firefox'
alias youtube-download-video='yt-dlp -f mp4 --cookies-from-browser firefox'
alias vpn='sudo openconnect --protocol=gp --user=$ADFS_USER_WORK --os=linux-64 $VPN_WORK_SRV'
alias radio="pyradio --play"
alias systemctl-f="sysz"
alias wtf="wtfutil"
alias news="newsboat -r"
alias curl_response_time="curl -s -w '\nLookup time:\t%{time_namelookup}\nConnect time:\t%{time_connect}\nPreXfer time:\t%{time_pretransfer}\nStartXfer time:\t%{time_starttransfer}\n\nTotal time:\t%{time_total}\n' -o /dev/null "
alias cls="/bin/ls"
alias ls="exa --header --icons --git --tree --level=1"
alias l="ls"
alias ll="ls -all"
alias lll="l -L 3 -D"
alias calc="bcal"
alias top="/usr/bin/btop"
alias top-max="/usr/bin/glances"
alias top-dns="/usr/bin/dnstop"
alias top-gpu="/usr/bin/nvtop"
alias top-disk='echo "Please run iotop with sudo rigths"'
alias top-netw='echo "Please run iftop with sudo rigths"'
alias top-power='echo "Please run powertop with sudo rigths"'
alias top-x-resources="/usr/bin/xrestop"
alias cat="/usr/bin/bat"
alias lg="/usr/bin/lazygit"
alias ld="/usr/bin/lazydocker"
alias bootstrap="$HOME/GIT/projects_home/dotfiles-public/bin/bootstrap.sh"
alias tw="taskwarrior-tui"
alias kafkacat="kcat"
alias log="lnav"
alias tsh-login="tsh login --proxy=$TELEPORT_PROXY"
alias gl="glab"
alias rg="rg -M 1000"
alias h="helm"
alias todo="todoist-cli"
alias td="todoist-cli q "
alias kk="k9s"
alias update-mirror='sudo reflector -c "Russia" -f 20 -l 20 -p https -p http -n 20 --save /etc/pacman.d/mirrorlist --sort rate'
alias update-apps="yay -Syu"
alias update-apps-clean-cache="yay -Scc && yay -Syu"
alias update-git-refs="$HOME/.config/polybar/git_update.sh"
alias helm-yc="HELM_DRIVER=sql HELM_DRIVER_SQL_CONNECTION_STRING='${HELM_POSTGRES_CONNECTION_STRING_STAGE_YC_1}' helm"
alias helm-sb="HELM_DRIVER=sql HELM_DRIVER_SQL_CONNECTION_STRING='${HELM_POSTGRES_CONNECTION_STRING_STAGE_SB_1}' helm"

# Extract anything alias
extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)  tar xjf $1    ;;
      *.tar.gz) tar xzf $1    ;;
      *.bz2)    bunzip2 $1    ;;
      *.rar)    rar x $1    ;;
      *.gz)   gunzip $1   ;;
      *.tar)    tar xf $1   ;;
      *.tbz2)   tar xjf $1    ;;
      *.tgz)    tar xzf $1    ;;
      *.zip)    unzip $1    ;;
      *.Z)    uncompress $1 ;;
      *)      echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Update smb-cli
#export PATH="$HOME/.go/bin:$HOME/.sbm-cli/usr/bin:$PATH"
#autoload -U compinit; compinit
#source /home/dvragulin/.sbm-cli/completion/zsh/sbm-cli

___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi
