---
# tasks file for git
                                                                            
- name: Link git config file | gitconfig home
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/04_Applications/git/files/gitconfig.home"
    dest: "$HOME/.gitconfig.home"
    state: link
    force: yes

- name: Link default git config file | gitconfig home
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/04_Applications/git/files/gitconfig.home"
    dest: "$HOME/.gitconfig"
    state: link
    force: yes

- name: Link git config file | gitconfig work
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/04_Applications/git/files/gitconfig.work"
    dest: "$HOME/.gitconfig.work"
    state: link
    force: yes
