---
# tasks file for k9s

- name: Link k9s config file | skin.yml
  file:
    src: "$HOME/GIT/projects_home/dotfiles-public/roles/k9s/files/skin.yml"
    dest: "$HOME/.config/k9s/skin.yml"
    state: link
    force: yes

