---
- name: Prepear Host
  hosts: DESKTOP
  become: yes
  roles:
    - _global


- name: Apply dotfiles
  hosts: DESKTOP
  become: no
  roles:
    - pacman
    - git
    - newsboat
    - i3
    - rtv
    - polybar
    - alacritty
    - taskwarrior
    - dunst
    - zsh
    - k8s
    - k9s
    - bash
    - ranger
    - rofi
    - btop
    - nvim
    - mc
    - ssh
    - zathura
    - tmux
    - xinit
    - terraform
    - feedbro
    - pyradio
    - gtk
    - got
    - avatars
    - keychron
    - lazygit
#    - vim

