---
- name: Prepear Host
  hosts: DESKTOP
  become: yes
  roles:
    - _prepare_workstation
    - _prepare_applications

- name: Apply dotfiles
  hosts: DESKTOP
  become: no
  roles:
    - avatars
    - bash
    - feedbro
    - git
    - ranger
    - rofi
    - ssh
    - tmux
    - vim
    - xinit
    - zsh 
    - mc
    - zathura

