---
- name: Prepear Host
  hosts: DESKTOP
  become: yes
  roles:
    - _global


- name: Apply dotfiles
  hosts: DESKTOP
  become: no
  roles:
    - git
    - newsboat
    - i3
    - polybar
    - alacritty
    - taskwarrior
    - dunst
    - zsh
    - k9s
    - pacseek
    - glow
    - bash
    - ranger
    - rofi
    - btop
    - helix
    - nvim
    - mc
    - ssh
    - zathura
    - tmux
    - xinit
    - pyradio
    - gtk
    - avatars
    - keychron
    - lazygit
    - vim
    - bluetooth
