---
- name: Get distribution
  hosts: localhost
  gather_facts: yes
  become: false
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

- name: Prepear Host
  hosts: DESKTOP
  become: yes
  roles:
    - _global


- name: Apply dotfiles
  hosts: DESKTOP
  become: no
  roles:
    - git
    - todoist
    - newsboat
    - i3
    - rtv
    - polybar
    - alacritty
    - dunst
    - zsh
    - k8s
    - k9s
    - bash
    - ranger
    - rofi
    - btop
    - vim
    - mc
    - ssh
    - zathura
    - tmux
    - xinit
    - feedbro
    - gtk
    - got
    - avatars
    - keychron

