---
# tasks file for _prepare_applications

- name: Upgrade all packages
  become: yes
  pacman: 
    upgrade: yes

- name: Install default packages
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  loop: "{{ default_packages }}"

- name: Install Snap packages
  snap:
    name: '{{ item }}'
    state: present
  loop: "{{ snap_packages }}"

- name: Install PIP packages
  pip:
    name: '{{ item }}'
    state: latest
  loop: "{{ pip_packages }}"

- name: Install packages
  shell: "yes | pamac install ansible-aur-git"   

- name: Install AUR packages
  aur:
    name: "{{ item }}"
    state: latest
  loop: "{{ aur_packages }}"                   
  become: false 

