---
# tasks file for _prepare_applications

- name: Upgrade all packages
  become: yes
  pacman: 
    upgrade: yes

- name: Install default packages
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  loop: "{{ default_packages }}"

- name: Install Snap packages
  snap:
    name: '{{ item }}'
    state: present
  loop: "{{ snap_packages }}"

- name: Install PIP packages
  pip:
    name: '{{ item }}'
    state: latest
  loop: "{{ pip_packages }}"

- name: Enable AUR in /etc/pamac.conf
  replace:
    path: /etc/pamac.conf
    regexp: "^#EnableAUR$"
    replace: "EnableAUR"

- name: Check AUR Updates in /etc/pamac.conf
  replace:
    path: /etc/pamac.conf
    regexp: "^#CheckAURUpdates$"
    replace: "CheckAURUpdates"

- name: Check AUR VCS Updates in /etc/pamac.conf
  replace:
    path: /etc/pamac.conf
    regexp: "^#CheckAURVCSUpdates$"
    replace: "CheckAURVCSUpdates"

- name: Install pamac packages
  shell: 'yes | pamac install {{ item }}'
  loop: "{{ pamac_packages }}"
 
