---
# tasks file for _global

- name: Prepear directories
  become: no
  file:
    path: '{{ item }}'
    state: directory
  loop:
  - '$HOME/Desktop'
  - '$HOME/Documents'
  - '$HOME/Documents/_Pictures'
  - '$HOME/Documents/_Desktop'
  - '$HOME/Downloads'
  - '$HOME/Icons'
  - '$HOME/Library'
  - '$HOME/Music'
  - '$HOME/Library'
  - '$HOME/NAS'
  - '$HOME/Shared'
  - '$HOME/tmp'
  - '$HOME/GIT'
  - '$HOME/GIT/projects_home'
  - '$HOME/GIT/projects_home/_ansible-collection'
  - '$HOME/GIT/projects_home/_docker-images'
  - '$HOME/GIT/projects_work'
  - '$HOME/GIT/projects_tests'
  - '$HOME/GIT/projects_monolith'
  - '$HOME/GIT/projects_infra'
  - '$HOME/GIT/projects_infra/_docker-images'
  - '$HOME/GIT/projects_infra/_k8s-installations'
  - '$HOME/GIT/projects_infra/_k8s-exporters'
  - '$HOME/GIT/projects_infra/_other'
  - '$HOME/GIT/projects_paas'
  - '$HOME/GIT/projects_paas/_docker-images'
  - '$HOME/GIT/projects_paas/_tools'
  - '$HOME/GIT/projects_paas/_platform'
  - '$HOME/GIT/projects_paas/_misc'
  - '$HOME/GIT/projects_products'
  - '$HOME/.tmp'
  - '$HOME/.tmp/Pictures'
  - '$HOME/.config'
  - '$HOME/.config/rofi'
  - '$HOME/.config/ranger'
  - '$HOME/.config/zathura'
  - '$HOME/.config/i3'
  - '$HOME/.config/polybar'
  - '$HOME/.config/alacritty'
  - '$HOME/.config/dunst'
  - '$HOME/.config/mc'
  - '$HOME/.config/newsboat'
  - '$HOME/.config/rtv'
  - '$HOME/.config/k9s'
  - '$HOME/.config/btop'
  - '$HOME/.config/got'
  - '$HOME/.config/yandex-disk'
  - '$HOME/.config/yandex-cloud'
  - '$HOME/.config/pyradio/'
  - '$HOME/.config/pyradio/themes'
  - '$HOME/.config/jesseduffield/lazygit'
  - '$HOME/.config/lazygit'
  - '$HOME/.config/glow'
  - '$HOME/.config/nvim'
  - '$HOME/.config/nvim/lua'
  - '$HOME/.config/nvim/autoload'
  - '$HOME/.neomutt'
  - '$HOME/.ssh'
  - '$HOME/.ssh/config.d'
  - '$HOME/.tmux'
  - '$HOME/.mutt'
  - '$HOME/.vim'
  - '$HOME/.kube'
  - '$HOME/.vim/autoload'
  - '$HOME/.ansible_vault'
  - '$HOME/.docker'
  - '$HOME/.scripts'
