---
# tasks list for _global

- name: Clone private repository
  git:
    repo: git@github.com:dvragulin/dotfiles-private.git
    version: master
    dest: $HOME/GIT/Projects_Home/dotfiles-private
    accept_hostkey: yes
  become: no

