---
# tasks file for _applications
                                                                            
- name: Link cat to bat
  become: yes
  file:
    src: "/usr/bin/bat"
    dest: "/bin/cat"
    state: link
    force: yes

- name: Link lazygit to lg
  become: yes
  file:
    src: "/usr/bin/lazygit"
    dest: "/usr/bin/lg"
    state: link
    force: yes

- name: Link lazydocker to ldocker
  become: yes
  file:
    src: "/usr/bin/lazydocker"
    dest: "/usr/bin/ldocker"
    state: link
    force: yes

- name: Link max user watches
  become: yes
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-public/roles/_global/files/50-max_user_watches.conf"
    dest: "/etc/sysctl.d/50-max_user_watches.conf"
    state: link
    force: yes

- name: Link locale.gen
  become: yes
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-public/roles/_global/files/locale.gen"
    dest: "/etc/locale.gen"
    state: link
    force: yes

- name: Link locale.conf
  become: yes
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-public/roles/_global/files/locale.conf"
    dest: "/etc/locale.conf"
    state: link
    force: yes
