---
# tasks list for _global

#- name: Clone private repository
#  git:
#    repo: git@github.com:dvragulin/dotfiles-private.git
#    version: master
#    dest: $HOME/GIT/Projects_Home/dotfiles-private
#    accept_hostkey: yes
#  become: no

- name: Link ssh private key
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/id_rsa"
    dest: "$HOME/.ssh/id_rsa"
    state: link
    force: yes
  become: no

- name: Link ssh public key
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/id_rsa.pub"
    dest: "$HOME/.ssh/id_rsa.pub"
    state: link
    force: yes
  become: no

- name: Link ssh config
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/config"
    dest: "$HOME/.ssh/config"
    state: link
    force: yes
  become: no

- name: Prepear config.d directory
  file:
    path: '$HOME/.ssh/config.d'
    state: directory

- name: Link ssh config.d/cloud_content
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/config.d/cloud_content"
    dest: "$HOME/.ssh/config.d/cloud_content"
    state: link
    force: yes
  become: no

- name: Link ssh config.d/cloud_prod
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/config.d/cloud_prod"
    dest: "$HOME/.ssh/config.d/cloud_prod"
    state: link
    force: yes
  become: no

- name: Link ssh config.d/cloud_stage
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/config.d/cloud_stage"
    dest: "$HOME/.ssh/config.d/cloud_stage"
    state: link
    force: yes
  become: no

- name: Link ssh config.d/cloud_stage
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ssh/config.d/cloud_stage"
    dest: "$HOME/.ssh/config.d/cloud_stage"
    state: link
    force: yes
  become: no

- name: Link KeePass DataBase
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/keepass/credentials.kdbx"
    dest: "$HOME/.cred.kdbx"
    state: link
    force: yes
  become: no

- name: Link kube config
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/kube/config"
    dest: "$HOME/.kube/config"
    state: link
    force: yes
  become: no

- name: Link ansible value stage
  file:
    src: "$HOME/GIT/Projects_Home/dotfiles-private/ansible_vault/stage"
    dest: "$HOME/.ansible_vault/srage"
    state: link
    force: yes
  become: no

