---
# tasks file for _applications

- name: Install pacman packages
  pacman:
    name: '{{ item }}'
    state: present
  loop: "{{ default_packages }}"

- name: Install Snap packages
  snap:
    name: '{{ item }}'
    state: present
  loop: "{{ snap_packages }}"

- name: Install PIP packages
  pip:
    name: '{{ item }}'
    state: latest
  loop: "{{ pip_packages }}"

- name: Install AUR packages
  become: false
  aur:
    name: "{{ item }}"
    state: latest
  loop: "{{ aur_packages }}"                   
