---
# tasks file for _applications

- name: Upgrade all packages
  become: yes
  pacman:
    upgrade: yes

- include_tasks: _install_apps.yml
- include_tasks: _install_i3.yml
- include_tasks: _make_links.yml
