---
# tasks file for keychron keyboard
- name: Link hid_apple.conf
  become: yes
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/02_Workstation/keychron/files/hid_config.conf"
    dest: "/etc/modprobe.d/hid_apple.conf"
    state: link
    force: yes

#- name: Link fnmode
#  file:
#    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/keychron/files/fnmode"
#    dest: "/sys/module/hid_apple/parameters/fnmode"
#    state: link
#    force: yes
#  become: yes