# https://github.com/challenger-deep-theme/alacritty
colors:
  # Default colors
  primary:
    background: '0x2B2B2B'
    foreground: '0xcbe3e7'

  # Normal colors
  normal:
    black:   '0x2B2B2B'
    red:     '0xB87A7A'
    green:   '0x7AB87A'
    yellow:  '0xD78700'
    blue:    '0x7A7AB8'
    magenta: '0xD78700'
    cyan:    '0x7AB8B8'
    white:   '0xcbe3e7'
   # white:   '0xD9D9D9'

  # Bright colors
  bright:
    black:   '0x2B2B2B'
    red:     '0x913434'
    green:   '0xBDDBBD'
    yellow:  '0xDBDBBD'
    blue:    '0xBDBDDB'
    magenta: '0xD78700'
    cyan:    '0xBDDBDB'
    white:   '0xa6b3cc'
#a1a7b4
window:
  dimensions:
    columns: 160
    lines: 50
  padding:
    x: 2
    y: 2
  dynamic_padding: true
  decorations: none
  #startup_mode: Maximized

scrolling:
  history: 100000

font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  size: 9.5

windows.opacity: 1

mouse:
  hints:
    launcher: xdg-open

