---
# tasks file for _prepare_workstation
                                                                            
- name: Link cat to bat
  become: yes
  file:
    src: "/usr/bin/bat"
    dest: "/bin/cat"
    state: link
    force: yes

- name: Link lazygit to lg
  become: yes
  file:
    src: "/usr/bin/lazygit"
    dest: "/usr/bin/lg"
    state: link
    force: yes

- name: Link lazydocker to ld
  become: yes
  file:
    src: "/usr/bin/lazydocker"
    dest: "/usr/bin/ld"
    state: link
    force: yes

