# -----------------------------------------------------------------------------
# K9s dvragulin theme
# -----------------------------------------------------------------------------

# Styles...
foreground: &foreground "#cbe3e7"
background: &background "#2b2b2b"
blue:       &blue       "#7a7ab8"
black:      &black      "#2b2b2b"
green:      &green      "#7ab87a"
grey:       &grey       "#cbe5e7"
magenta:    &magenta    "#7ab87a"
orange:     &orange     "#ffb86c"
red:        &red        "#b87a7a"
yellow:     &yellow     "#d78700"

# Skin...
k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
    border:
        command: *green
        default: *foreground
  info:
    fgColor: *magenta
    sectionColor: *green
  dialog:
    fgColor: *black
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *green
    buttonFocusFgColor: *black
    buttonFocusBgColor: *blue
    labelFgColor: *orange
    fieldFgColor: *blue
  frame:
    border:
      fgColor: *green
      focusColor: *green
    menu:
      fgColor: *grey
      keyColor: *yellow
      numKeyColor: *yellow
    crumbs:
      fgColor: *black
      bgColor: *green
      activeColor: *yellow
    status:
      newColor: *blue
      modifyColor: *green
      addColor: *grey
      errorColor: *red
      highlightColor: *yellow
      killColor: *green
      completedColor: *grey
    title:
      fgColor: *blue
      bgColor: *background
      highlightColor: *green
      counterColor: *foreground
      filterColor: *blue
  views:
    charts:
      bgColor: *background
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *green
        - *red
    table:
      fgColor: *yellow
      bgColor: *background
      cursorFgColor: *black
      cursorBgColor: *blue
      header:
        fgColor: *grey
        bgColor: *background
        sorterColor: *orange
    xray:
      fgColor: *blue
      bgColor: *background
      cursorColor: *foreground
      graphicColor: *yellow
      showIcons: true
    yaml:
      keyColor: *blue
      colonColor: *grey
      valueColor: *grey
    logs:
      fgColor: *grey
      bgColor: *background
      indicator:
        fgColor: *blue
        bgColor: *background
        toggleOnColor: *magenta
        toggleOffColor: *blue
    help:
      fgColor: *grey
      bgColor: *background
      indicator:
        fgColor: *blue
