# OneDark presets
foreground: &foreground "#cbe3e7"
background: &background "#2b2b2b"
black: &black "#2b2b2b"
blue: &blue "#7a7ab8"
green: &green "#7ab87a"
grey: &grey "#cbe5e7"
orange: &orange "#ffb86c"
purple: &purple "#7ab87a"
red: &red "#b87a7a"
yellow: &yellow "#d78700"
yellow_bright: &yellow_bright "#dbdbbd"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *green
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *grey
    sectionColor: *green
  dialog:
    fgColor: *black
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *green
    buttonFocusFgColor: *black
    buttonFocusBgColor: *blue
    labelFgColor: *orange
    fieldFgColor: *blue
  frame:
    border:
      fgColor: *green
      focusColor: *green
    menu:
      fgColor: *grey
      keyColor: *yellow
      numKeyColor: *yellow
    crumbs:
      fgColor: *black
      bgColor: *green
      activeColor: *yellow
    status:
      newColor: *blue
      modifyColor: *green
      addColor: *grey
      pendingColor: *orange
      errorColor: *red
      highlightcolor: *yellow
      killColor: *green
      completedColor: *grey
    title:
      fgColor: *blue
      bgColor: *background
      highlightColor: *green
      counterColor: *foreground
      filterColor: *blue
  views:
    charts:
      bgColor: *background
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *green
        - *red
    table:
      fgColor: *yellow
      bgColor: *background
      cursorFgColor: *black
      cursorBgColor: *blue
      markColor: *yellow_bright
      header:
        fgColor: *grey
        bgColor: *background
        sorterColor: *orange
    xray:
      fgColor: *blue
      bgColor: *background
      cursorColor: *foreground
      graphicColor: *yellow_bright
      showIcons: true
    yaml:
      keyColor: *red
      colonColor: *grey
      valueColor: *grey
    logs:
      fgColor: *grey
      bgColor: *background
      indicator:
        fgColor: *blue
        bgColor: *background
    help:
      fgColor: *grey
      bgColor: *background
      indicator:
        fgColor: *blue
