theme = "darcula"

[editor]
line-number = "absolute"
auto-completion = true
auto-info	= true
auto-format = false
rulers = [120]

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[keys.normal]
"W" = ["select_mode", "goto_line_end", "normal_mode"]
"C-/" = ["toggle_comments", "move_visual_line_down"]

