use-grammars = { except = ["gemini"] }

[[language]]
name = "go"
language-servers = ["gopls"]

[language-server.gopls.config]
gofumpt = true
memoryMode = "DegradeClosed"
deepCompletion = true
staticcheck = true

[[language]]
name = "yaml"

[language-server.yaml-language-server.config]
yaml.keyOrdering = false
