[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = false
[language-server.gopls.config]
gofumpt = true
memoryMode = "DegradeClosed"
deepCompletion = true
staticcheck = true

[[language]]
name = "yaml"
auto-format = false
[language-server.yaml-language-server.config]
yaml.keyOrdering = false
staticcheck = true

[[language]]
name = "bash"
auto-format = false
[language-server.bash-language-server.config]
staticcheck = true

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = false
