---
# defaults file for _applications

pacman_packages:
  - base-devel
  - vim
  - vim-runtime
  - vscode
  - rofi
  - openssh
  - gparted
  - net-tools
  - rsync
  - ntfs-3g
  - vagrant
  - tcpdump
  - snappy
  - pulsemixer
  - guake
  - ranger
  - tldr
  - tmux
  - ncdu
  - qbittorrent
  - duf
  - firefox
  - mc
  - gnupg
  - pass
  - fd
  - bat
  - exa
  - jq
  - thunderbird
  - calibre
  - vlc
  - rhythmbox
  - obs-studio
  - pgadmin4
  - python-pip
  - llvm
  - tree
  - make
  - htop
  - dolphin
  - viewnior
  - ipython
  - speedtest-cli
  - telegram-desktop
  - lazygit
  - asciinema
  - zathura               # PDF Reader
  - zathura-pdf-poppler   # PDF Reader plugin
  - zathura-djvu          # PDF Reader plugin
  - zathura-ps            # PDF Reader plugin
  - alacritty             # Best terminal
  - discord               # Voice chat
  - zsh
  - w3m
  - w3m-imgcat
  - aerc
  - pcmanfm
  - traceroute
  - ueberzug
  - putty
  - terraform
  - httpie
  - keepassxc
  - aws-cli
  - kubectl
  - postgresql
  - phpmyadmin
  - mysql-workbench
  - gtk3
  - gobject-introspection
  - webkit2gtk
  - mpv
  - unzip
  - ripgrep
  - minikube
  - virt-manager
  - qemu
  - vde2
  - dnsmasq
  - bridge-utils
  - openbsd-netcat
  - gpg-tui
  - newsboat                    # Rss reader
  - lynx
aur_packages:
  - rxvt                        # Terminal
  - termdbms
  - network-manager-applet      # Applet for network manager
  - ncurses                     # Libs
  - chromedriver                # Chromedriver
  - git-delta                   # Diff tool
  - wakeonlan                   # Tool for send wakeup
  - lazydocker                  # TUI for Docker 
  - hstr                        # History tool
  - bottom
  - vte3
  - gtk2-perl
  - glab                        # GitLab cli
  - dockle                      # Container diagnostic tool
  - asbru-cm                    # SSH GUI Client
  - zoom                        # Voice/Video chat
  - google-chrome               # Web browser
  - etcher                      # USB boot
  - ttf-unifont                 # Fonts
  - ttf-weather-icons           # Weather
  - siji-git                    # Fonts
  - tfswitch
  - lens-bin                    # k8s GUI cloent
  - yandex-cloud-bin            # Yandex Cloud CLI
  - gp-saml-gui                 # VPN Software
  - globalprotect-openconnect   # VPN Software
  - yandex-music-player         # Music player
  - terraformer
  - transmission-remote-tui-git # Torrent client
  - helm                        # k8s deploy tool
  - duck
  - k9s                         # k8s tui tool
  - multiwerf-bin
  - urlview
  - docker
  - docker-compose
  - cointop-bin
  - fzf                         # Fuzzy finder
  - fx
  - gucharmap 
  - dive
  - rtv
  - wuzz
  - s3cmd
  - ytfzf
  - termshark
  - markdown
  - dbeaver
  - dnsutils
  - yt-dlp
  - goaccess
  - postman-bin
  - kafkacat-git
  - ethr
  - makepasswd
  - grpcurl
  - yandex-disk
  - btop                        # Pretty Top :) 
  - smartgit
  - yq
  - jmtpfs
  - pyradio                     # Tool for radio
  - ctags
  - flog
  - sysz
  - grv
  - flameshot
  - browsh
  - taskwarrior-tui             # Todo manager tui
snap_packages:
  - mattermost-desktop
  - whatsdesk
  - skype
  - core20
  - matterhorn
snap_classic_packages:
  - powershell
  - pycharm-community
pip_packages:
  - requests
  - jinja2
  - flake8
  - pyflakes
  - pylint
  - ipython
  - prettytable
  - gitpython
  - pipenv
  - pandas
  - pendulum
  - jira
  - grip
  - google-auth-httplib2
  - google-auth-oauthlib
  - notion-backup
  - yandex-music                 # Client for Yandex Music
  - oauth2client
  - todoist-api-python           # Lib for todoist
#  - google-api-python-client
fonts_packages:
  - ttf-ubuntu-font-family
  - ttf-font-awesome
  - ttf-freefont
  - ttf-liberation
  - ttf-droid
  - ttf-roboto
  - ttf-hack
  - noto-fonts
  - terminus-font
  - arc-gtk-theme
  - papirus-icon-theme

i3_packages:
  - i3-wm
  - i3status
  - polybar
  - feh
  - numlockx
  - lightdm
  - lightdm-gtk-greeter
  - lxappearance
  - dunst

packages_to_delete:
  - spectacle
  - cantata
  - gwenview
  - kate
  - skanlite
  - okular
  - steam-manjaro
  - konversation
  - qbittorrent
  - pidgin
  - k3b
  - yakuake
  - kfind
  - kdeconnect
  - virtualbox
  - virtualbox-host-dkms
  - virtualbox-sdk
  - kget
