---
# defaults file for _applications

pacman_packages:
  - openssh
  - net-tools
  - rsync
  - ntfs-3g
  - virtualbox
  - vagrant
  - snappy
  - guake
  - vim
  - ranger
  - tldr
  - tmux
  - ncdu
  - mc
  - fd
  - bat
  - exa
  - jq
  - thunderbird
  - calibre
  - pidgin
  - vlc
  - obs-studio
  - youtube-dl
  - pgadmin4
  - python-pip
  - llvm
  - make
  - htop
  - shotwell
  - ipython
  - telegram-desktop
  - lazygit
  - asciinema
  - zathura
  - zathura-pdf-poppler
  - zathura-djvu
  - zathura-ps
  - alacritty
  - zsh

aur_packages:
  - chromedriver
  - git-delta
  - wakeonlan
  - woeusb-gui
  - lazydocker
  - hstr
  - vte3
  - gtk2-perl
  - asbru-cm
  - trello
  - zoom
  - google-chrome
  - etcher

snap_packages:
  - discord
  - bitwarden
  - postman
  - whatsdesk
  - mattermost-desktop
  - skype

snap_classic_packages:
  - gitkraken
  - powershell
  - pycharm-community
  - slack

pip_packages:
  - requests
  - jinja2
  - flake8
  - prettytable
  - gitpython

i3_packages:
  - xorg-server
  - xorg-apps
  - xorg-xinit
  - i3-gaps
  - i3blocks
  - numlockx
  - lightdm
  - lightdm-gtk-greeter
  - noto-fonts
  - ttf-ubuntu-font-family
  - ttf-dejavu
  - ttf-freefont
  - ttf-liberation
  - ttf-droid
  - ttf-roboto
  - terminus-font
