---
- name: Link bootstrap
  become: yes
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/bin/bootstrap.sh"
    dest: "/usr/bin/bootstrap"
    state: link
    force: yes

- name: Link ~/Documents/_Pictures to Pictures
  become: yes
  file:
    src: "/home/dvragulin/Documents/_Pictures"
    dest: "/home/dvragulin/Pictures"
    state: link
    force: yes

- name: Link ~/Documents/_Video to Video
  become: yes
  file:
    src: "/home/dvragulin/Documents/_Video"
    dest: "/home/dvragulin/Video"
    state: link
    force: yes

- name: Link ~/Documents/_Desktop to Desktop
  become: yes
  file:
    src: "/home/dvragulin/Documents/_Desktop"
    dest: "/home/dvragulin/Desktop"
    state: link
    force: yes

- name: Link ~/Documents/_Shared to Shared
  become: yes
  file:
    src: "/home/dvragulin/Documents/_Shared"
    dest: "/home/dvragulin/Shared"
    state: link
    force: yes
