---
# tasks file for got

- name: Link got config file | btop.conf
  file:
    src: "$HOME/GIT/projects_home/dotfiles-public/roles/got/files/config.yml"
    dest: "$HOME/.config/got/config.yml"
    state: link
    force: yes

