---
# tasks file for tmux
                                                                            
- name: Link bash config file | tmux.conf
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/04_Applications/tmux/files/tmux.conf"
    dest: "$HOME/.tmux.conf"
    state: link
    force: yes

- name: Link bash config file | .tmux.conf.local
  file:
    src: "/home/dvragulin/GIT/projects_home/dotfiles-public/roles/04_Applications/tmux/files/tmux.conf.local"
    dest: "$HOME/.tmux.conf.local"
    state: link
    force: yes

#- name: Apply configuration
#  become: false
#  command: "tmux source $HOME/.tmux.conf"

# $ git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# ctrl + a / alt + shift + i
